-- Seed file for Terrashare Properties based on client feedback
-- Run this script in your Supabase SQL Editor to insert the new properties

INSERT INTO public.properties (
  title, 
  slug, 
  location, 
  description, 
  image_urls, 
  min_investment, 
  returns_percent, 
  duration_months, 
  payout_style, 
  category, 
  type_details, 
  is_fractional, 
  unit_value, 
  total_units, 
  status
) VALUES 
(
  'Federal University Hostel (Fractional Investment)', 
  'federal-university-hostel-investment', 
  'University Campus', 
  'Investment in Federal University hostel deals. High demand student housing.', 
  ARRAY['https://images.unsplash.com/photo-1555854877-bab0e564b8d5?q=80&w=800&auto=format&fit=crop'], 
  100000, 
  25, 
  18, 
  'after_maturity', 
  'residential', 
  '{}'::jsonb, 
  true, 
  null, 
  null, 
  'open'
),
(
  'Federal University Hostel (Outright Purchase)', 
  'federal-university-hostel-outright', 
  'University Campus', 
  'Outright purchase of a hostel room (26sqm). Currently off-plan. Estimated rental income is ₦2,000,000 yearly.', 
  ARRAY['https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?q=80&w=800&auto=format&fit=crop'], 
  15000000, 
  13.33, 
  12, 
  'after_maturity', 
  'residential', 
  '{"area": "26sqms", "stage": "off plan", "payment_plan": "₦500,000 monthly", "rental_income_yearly": 2000000, "ownership": "Sole ownership"}'::jsonb, 
  false, 
  15000000, 
  1, 
  'open'
),
(
  'Federal University Hostel (Co-Own)', 
  'federal-university-hostel-co-own', 
  'University Campus', 
  'Co-own a hostel room. Each room occupies 4 students. Estimated rental income per slot is ₦500,000.', 
  ARRAY['https://images.unsplash.com/photo-1505691938895-1758d7feb511?q=80&w=800&auto=format&fit=crop'], 
  3250000, 
  15.38, 
  12, 
  'after_maturity', 
  'residential', 
  '{"occupancy": "4 students per room", "rental_income_per_slot": 500000}'::jsonb, 
  true, 
  3250000, 
  4, 
  'open'
),
(
  'Work Station Deals', 
  'work-station-deals', 
  'City Center', 
  'Investment in this property suitable for office and work place for start ups.', 
  ARRAY['https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=800&auto=format&fit=crop'], 
  150000, 
  15, 
  6, 
  'after_maturity', 
  'commercial', 
  '{}'::jsonb, 
  true, 
  null, 
  null, 
  'open'
),
(
  'Fastest Growing Estate in Lekki Corridor', 
  'lekki-corridor-estate', 
  'Lekki Corridor, Lagos', 
  'Investment in the fastest growing estate in the Lekki corridor. Currently 50% completed.', 
  ARRAY['https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=800&auto=format&fit=crop'], 
  500000, 
  25, 
  15, 
  'after_maturity', 
  'residential', 
  '{"stage": "50% completed"}'::jsonb, 
  true, 
  null, 
  null, 
  'open'
),
(
  '4 Bedroom Detached House - Beechwood Estate', 
  '4-bed-detached-beechwood', 
  'Beechwood Estate, Lekki Axis', 
  'A Newly finished 4 bedroom detached House. House garage Packs 10 cars conveniently. 24Hrs Electricity. Concrete road Networks with adequate drainage. Gated serene Environment. 24hrs Security.', 
  ARRAY['https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?q=80&w=800&auto=format&fit=crop'], 
  100000000, 
  5.35, 
  12, 
  'monthly', 
  'residential', 
  '{"purchase_cost": 280000000, "legal_fee": 14000000, "administrative_fee": 6000000, "expected_rental_income": 15000000, "payment_plan": "100million Deposit, 15million monthly", "duration_months": 12, "ownership_type": "Sole ownership", "title": "C of O, Deed of Assignment, Registered Survey, Building permit", "landmarks": ["Lakowe Golf course", "New Lagos seaport", "proposed New Airport"]}'::jsonb, 
  false, 
  280000000, 
  1, 
  'open'
);
